name: Notify via Telegram

on:
  push:
    branches:
      - main  # Trigger this action on pushes to the main branch

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        run: |
          curl -X POST \
            "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=🚀 New push to ${{ github.ref }} by ${{ github.actor }}. Commit message: '${{ github.event.head_commit.message }}'"
