name: Telegram Notification

on:
  push:
    branches:
      - main  # Trigger on push to main branch; adjust this as needed

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send Telegram Notification
        run: |
          curl -X POST \
          "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=🚀 New push to main branch! Commit message: '${{ github.event.head_commit.message }}'"
